"""empty message

Revision ID: 021f0bc2a3ad
Revises: b2ac317e6657
Create Date: 2019-01-22 09:34:17.120557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021f0bc2a3ad'
down_revision = 'b2ac317e6657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'test_beizhu', 'test_case', ['case_id'], ['id'])
    op.create_foreign_key(None, 'test_case', 'test_task', ['task_chandao'], ['chandao'])
    op.add_column('test_task', sa.Column('username', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_test_task_username'), 'test_task', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_task_username'), table_name='test_task')
    op.drop_column('test_task', 'username')
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_constraint(None, 'test_beizhu', type_='foreignkey')
    # ### end Alembic commands ###
