"""empty message

Revision ID: 0668529f84be
Revises: 7238b69c9d72
Create Date: 2019-01-14 14:54:37.955801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0668529f84be'
down_revision = '7238b69c9d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'test_case', 'test_task', ['task_chandao'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    # ### end Alembic commands ###
