"""empty message

Revision ID: 37088bfafdcb
Revises: fcf4c6332fd1
Create Date: 2019-01-12 09:54:58.246768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37088bfafdcb'
down_revision = 'fcf4c6332fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('is_validation', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_case', 'test_task', ['task_chandao'], ['id'])
    op.drop_column('test_case', 'inlineCheckbox2')
    op.drop_column('test_case', 'inlineCheckbox1')
    op.drop_column('test_case', 'inlineCheckbox3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('inlineCheckbox3', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('test_case', sa.Column('inlineCheckbox1', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('test_case', sa.Column('inlineCheckbox2', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_column('test_case', 'is_validation')
    # ### end Alembic commands ###
