"""empty message

Revision ID: 7238b69c9d72
Revises: a7a1a44107f7
Create Date: 2019-01-14 14:30:02.391404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7238b69c9d72'
down_revision = 'a7a1a44107f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case', 'task_chandao',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'test_case', 'test_task', ['task_chandao'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.alter_column('test_case', 'task_chandao',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
