"""empty message

Revision ID: a7a1a44107f7
Revises: 37088bfafdcb
Create Date: 2019-01-14 14:21:50.760284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7a1a44107f7'
down_revision = '37088bfafdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('casenote', sa.String(length=500), nullable=True))
    op.alter_column('test_case', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'test_case', 'test_task', ['task_chandao'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.alter_column('test_case', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('test_case', 'casenote')
    # ### end Alembic commands ###
