"""empty message

Revision ID: b2ac317e6657
Revises: 64560450e0ab
Create Date: 2019-01-14 16:56:39.442566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2ac317e6657'
down_revision = '64560450e0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_beizhu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('casenote', sa.String(length=500), nullable=True),
    sa.Column('datatime', sa.DateTime(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['test_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'test_case', 'test_task', ['task_chandao'], ['chandao'])
    op.drop_column('test_case', 'casenote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('casenote', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_table('test_beizhu')
    # ### end Alembic commands ###
