"""empty message

Revision ID: fa602dade76c
Revises: cead96b7334d
Create Date: 2019-01-10 15:27:56.187846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa602dade76c'
down_revision = 'cead96b7334d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'test_case', 'test_task', ['task_chandao'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    # ### end Alembic commands ###
