"""empty message

Revision ID: fcf4c6332fd1
Revises: fa602dade76c
Create Date: 2019-01-12 08:33:59.313853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcf4c6332fd1'
down_revision = 'fa602dade76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('inlineCheckbox1', sa.String(length=10), nullable=True))
    op.add_column('test_case', sa.Column('inlineCheckbox2', sa.String(length=10), nullable=True))
    op.add_column('test_case', sa.Column('inlineCheckbox3', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_test_case_id'), 'test_case', ['id'], unique=False)
    op.create_foreign_key(None, 'test_case', 'test_task', ['task_chandao'], ['id'])
    op.drop_column('test_case', 'is_validation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('is_validation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_index(op.f('ix_test_case_id'), table_name='test_case')
    op.drop_column('test_case', 'inlineCheckbox3')
    op.drop_column('test_case', 'inlineCheckbox2')
    op.drop_column('test_case', 'inlineCheckbox1')
    # ### end Alembic commands ###
